[project]
name = "SnakeGameAIDRQN"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.4.0",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pygame>=2.6.1",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
